### ISSUE TITLE
add an option to generate range

### ISSUE THREAD

**Issue by aladdin-add** [pvdz/tenko#11]
to play well with eslint, can you add a option to generate `range`  property

refs: https://eslint.org/docs/developer-guide/working-with-custom-parsers#all-nodes

> The AST specification
> The AST that custom parsers should create is based on ESTree. The AST requires some additional properties about detail information of the source code.
> 
> All nodes:
> All nodes must have range property.
> 
> range (number[]) is an array of two numbers. Both numbers are a 0-based index which is the position in the array of source code characters. The first is the start position of the node, the second is the end position of the node. code.slice(node.range[0], node.range[1]) must be the text of the node. This range does not include spaces/parentheses which are around the node.
> loc (SourceLocation) must not be null. The loc property is defined as nullable by ESTree, but ESLint requires this property. On the other hand, SourceLocation#source property can be undefined. ESLint does not use the SourceLocation#source property.
> The parent property of all nodes must be rewritable. ESLint sets each node's parent property to its parent node while traversing, before any rules have access to the AST.

**Comment by pvdz** [comment]
I'll have a look into this. Locs are generated centrally so I guess there's no real harm in an extra branch there.

**Comment by pvdz** [comment]
As I'm looking into this, I guess I've already added this option? Is that not what you're looking for?

I see I did not document it in the README so I'll fix that. If it's insufficient please reopen and let me know what's missing :)

**Comment by aladdin-add** [comment]
I guess so. it was namesd `ranges`, but not documented.

I found the espree output ranges like this:
![image](https://user-images.githubusercontent.com/13050025/106592591-abf84980-658a-11eb-9b1e-44d93e3b2f36.png)

but tenko output is:
![image](https://user-images.githubusercontent.com/13050025/106592688-c9c5ae80-658a-11eb-9d87-4aac79fac101.png)

if you want to change it, glad to make a PR. :)

**Comment by pvdz** [comment]
Yeah it's a range array on the node itself rather than in loc. I'll add something but it's a little more involved since half the nodes are not created through one funnel (whereas the locs all go through one function). Anyways, should have something soon, in case that still matters :)

**Comment by pvdz** [comment]
I hope I got them all but I just pushed an option `nodeRange` which should do what you requested. Let me know if it works as intended. Thanks :)

**Comment by aladdin-add** [comment]
seems it was missing in the root node, otherwise looks good to me!
![image](https://user-images.githubusercontent.com/13050025/106852801-9d797180-66f3-11eb-8e30-2e9c63c0f790.png)

**Comment by aladdin-add** [comment]
and, is there an option to generate comments? ( I did not find it in the readme)
