### ISSUE TITLE
realpath: command not found

### ISSUE THREAD

**Issue by aladdin-add** [pvdz/tenko#12]
```bash
➜  tenko git:(master) ✗ ./t
./t: line 8: realpath: command not found
usage: dirname path
./tests/t.sh: line 6: realpath: command not found
usage: dirname path
./tests/t.sh: line 258: syntax error near unexpected token `;'
```

os: macos 11.2 Beta (20D5029f)

**Comment by pvdz** [comment]
There appears to be no equivalent of `realpath` on macos, beyond brew installing coreutils (see https://stackoverflow.com/questions/3572030/bash-script-absolute-path-with-os-x).

The only reason I use this is to get the actual folder of the current script, to make sure all commands can be safely executed assuming being in the correct folder. Do you have a better proposal that works on both mac and linux?

**Comment by pvdz** [comment]
From `t.sh`:
```
# https://stackoverflow.com/questions/59895/how-to-get-the-source-directory-of-a-bash-script-from-within-the-script-itself
# https://stackoverflow.com/questions/7665/how-to-resolve-symbolic-links-in-a-shell-script
# Move to the folder where this script lives (should be `**/tenko/tests/t.sh`)
cd "$( dirname $(realpath "${BASH_SOURCE[0]}") )" >/dev/null 2>&1
```

**Comment by mischnic** [comment]
What about `node -p 'fs.realpathSync("...")'` ?

**Comment by pvdz** [comment]
Considering we're gonna use node anyways, that makes sense. Bit of a chicken egg problem in terms of which node binary to use here. Maybe not very relevant for this particular case.

**Comment by pvdz** [comment]
Thanks :) :green_heart:

**Comment by aladdin-add** [comment]
it seems `realpath` is also used in `./t`https://github.com/pvdz/tenko/blob/a066b4af4e7cddb4a73fe4df43cf89033505a78e/t#L8

and, after fixing it, there was a new error:
```bash
➜  tenko git:(master) ✗ ./t --help
./tests/t.sh: line 259: syntax error near unexpected token `;'
```

**Comment by pvdz** [comment]
Eliminated the other use of `realpath` as well.

I'm not sure what line it's throwing over. Is it not liking this bit?

```
    c8);&
    coverage):
```

Cause I'm not sure what the clean alternative is here.

**Comment by aladdin-add** [comment]
![image](https://user-images.githubusercontent.com/13050025/106691268-2ddd8680-660e-11eb-8465-44b0ec06c63a.png)


I also did test on my ubuntu, it's working fine.
