### ISSUE TITLE
Tokens format not compatible with Esprima and other parsers

### ISSUE THREAD

**Issue by coderaiser** [pvdz/tenko#6]
[esprima](https://github.com/jquery/esprima) and `babel`, `estree`, `acorn` has tokens format that has `loc` field:

```json
{
    "loc": {
        "start": {
            "line": 8,
            "column": 4
         },
         "end": {
             "line": 8,
             "column": 8
         }
    }
} 
```

Would be great if `tenko` also has it because [recast uses esprima](https://github.com/benjamn/recast/blob/v0.18.5/lib/parser.ts#L40-L54) if it can't find `tokens` field, but it works great for parsers mentioned earlier.

So compatible tokens field is crucial to avoid double parsing.

**Comment by pvdz** [comment]
So the tokens get the locs? Sure that can be done.

I will make it optional as it adds a tax to the GC while the parser doesn't use or need it.

**Comment by pvdz** [comment]
Sorry for the delay, but here you go :)

**Comment by coderaiser** [comment]
Don't you forget to rebuild `tenko.prod.js`? Just updated, flag doesn't works for me.
