### ISSUE TITLE
yarn install fails

### ISSUE THREAD

**Issue by tmikov** [pvdz/tenko#7]
```
yarn install
Using globally installed version of Yarn
yarn install v1.12.1
warning package.json: No license field
info No lockfile found.
warning tenko@1.0.6: No license field
[1/4] 🔍  Resolving packages...
error Can't add "acorn": invalid package version undefined.
```

If I try npm, it hangs at:
```
⸨    ░░░░░░░░░░░░░░⸩ ⠋ fetchMetadata: sill resolveWithNewModule is-wsl@1.1.0 checking installable status
```

I wonder whether this could be something in my environment (FB laptop), but other things seem to work.

**Comment by pvdz** [comment]
Yeah this is weird. @arcanis do you have any idea? 

The acorn package exists: https://www.npmjs.com/package/acorn/v/7.1.0

(npm, apart from being slow, has no problem with this)

The package.json looks like this:

```
{
  "name": "tenko",
  "version": "1.0.6",
  "author": "Peter van der Zee",
  "description": "A \"pixel perfect\" 100% spec compliant ES2020 JavaScript parser written in JS.",
  "main": "build/tenko.prod.js",
  "module": "build/tenko.prod.mjs",
  "devDependencies": {
    "@babel/parser": "7.6.4",
    "acorn": "7.1.0",
    "deoptigate": "0.5.0",
    "esfuzz": "0.3.1",
    "eslump": "2.0.0",
    "prettier": "1.18.2",
    "terser": "4.3.3"
  },
```

**Comment by arcanis** [comment]
`esfuzz` depends on `acorn` through a git dependency: https://cdn.jsdelivr.net/npm/esfuzz@0.3.1/package.json

The problem is that the referenced repository doesn't contain a valid manifest (no version):
https://github.com/acornjs/acorn/blob/master/package.json

**Comment by pvdz** [comment]
Ah that makes sense. Thanks :)

I'll think about how to work around this. Perhaps just dropping it altogether, or trying to get it fixed upstream, or forking, or smth.

**Comment by pvdz** [comment]
Just dropped it because why not. Last commit was 6 years old. I'm sure there's more up to date fuzzers out there.
